name: CI Pipeline

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: echo "Build success"

      - name: Test
        run: echo "Test passed"

      - name: Scan
        run: echo "Scan done"
